### PR TITLE
docs: new homepage

### PR DESCRIPTION
**Pull request by adamraider**
image

### CODE REVIEW

**Comment by cmugla** [comment]
FYI - the search bar overlaps the hamburger on mobile:

Screen Shot 2019-06-19 at 1 49 19 AM

**Comment by cmugla** [comment]
I'm not the hugest fan of splash pages - what is the reason for this addition?

**Comment by adamraider** [comment]
> I'm not the hugest fan of splash pages - what is the reason for this addition?

@cmugla Set's the tone for the system to newcomers. Easy reference page for important links, docs, github, npm.

**Comment by adamraider** [comment]
> FYI - the search bar overlaps the hamburger on mobile:

@cmugla I know. :(

I'm not a huge fan of the implementation of the search by either, if you have any ideas pls lmk!

**Pull request merged**
